################ Spanish language ##################
[es]
languageName = "ğŸŒ ES"
languageCode = "es-co"
contentDir = "content/es"
weight = 1
################ English language ##################
[en]
languageName = "ğŸ‡ºğŸ‡¸ EN"
languageCode = "en-us"
contentDir = "content/en"
weight = 2