#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
logo_darkmode = "images/logo-darkmode.png"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "160px"
logo_height = "32px"
# if logo_webp set false, will not generate WEBP version of logo | default is true
logo_webp = true
# logo text will only show when logo is missing.
logo_text = "AMBULANCIAS"
# navbar fixed to top
navbar_fixed = true
# theme-mode
theme_switcher = true
theme_default = "system" # available options [light/dark/system]
# Main Sections
mainSections = ["blog", "libros"]
# contact form action
contact_form_action = "#" # contact form works with [https://airform.io/] or [https://formspree.io]
# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "" # example: G-XXXXXXXXXX
google_adsense = ""     # example: ca-pub-xxxxxxxxxxxxxxxx
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script = ""
# copyright
copyright = "Desarrollo web por [Hakesh](https://www.instagram.com/hakeshdigital/)"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "contacto"
link = "/es/contacto"

# search
[search]
enable = true
primary_color = "#DE1600"
include_sections = ["blog"]
show_image = true
show_description = true
show_tags = true
show_categories = true

# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["Ambulancias", "Veh√≠culos de emergencia", "ambulancias en venta", "comprar ambulancias", "servicios de emergencia", "atenci√≥n m√©dica de urgencia", "tecnolog√≠a m√©dica", "profesionales de la salud", "Am√©rica Latina"]
description = "Especialistas en Venta, Mantenimiento y Adecuaci√≥n de Ambulancias en Latinoam√©rica. Descubre la mejor informaci√≥n sobre ambulancias, servicios de emergencia, tecnolog√≠a m√©dica y m√°s en AMBULANCIAS üöëÔ∏è LAT. Estamos comprometidos con brindar contenido relevante y actualizado para profesionales y entusiastas de la salud de emergencia en Am√©rica Latina."
title = "Ambulancias Latinoamericanas üöëÔ∏è"
author = "@HakeshDigital"
image = "images/og-image.jpg"


# site verifications
[site_verification]
google = ""   # Your verification code
bing = ""     # Your verification code
baidu = ""    # Your verification code
facebook = "" # Your verification code
mastodon = "" # Your verification code

# cookies
[cookies]
enable = false
expire_days = 60
content = "Este sitio utiliza cookies. Al continuar utilizando este sitio web, aceptas su uso."
button = "Acepto"

######################## sidebar widgets #########################
[widgets]
sidebar = ["categories", "tags"]


# google map
[google_map]
enable = false
#map_api_key = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
#map_latitude = "51.5223477"
#map_longitude = "-0.1622023"
#map_marker = "images/marker.png"


# Subscription
[subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
